# to run compose
## docker-compose -f devops/docker-compose.yml up -d
# to stop compose
## docker-compose -f devops/docker-compose.yml down

version: '3'
services:
  backend:
    build:
      context: ../
      dockerfile: devops/dockerfile
    restart: always
    ports:
      - 3001:3001
    environment:
      PORT: 3001
